import { Backdrop, Button, Dropdown } from "components/common";
import { GuestSidebar } from "components/navigation";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React, { ReactNode, useMemo, useState } from "react";
import { Menu } from "react-feather";
import { Category } from "service/types/category_type";
import GuestFooter from "./footer/GuestFooter";

interface GuestLayoutProps {
  title: string;
  children: ReactNode;
  categories: Category[];
}

function GuestLayout(props: GuestLayoutProps) {
  const { title, children, categories } = props;
  const router = useRouter();
  const employersList = useMemo(() => {
    return [
      {
        title: "Post a Job",
        route: "",
      },
      {
        title: "Pricing",
        route: "",
      },
      {
        title: "Create Employer Account",
        route: "",
      },
      {
        title: "Sign In",
        route: "",
      },
    ];
  }, []);

  const [openSidebar, setOpenSidebar] = useState(false);
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative">
        <GuestSidebar
          categories={categories}
          onClose={() => setOpenSidebar(false)}
          open={openSidebar}
          employersMenu={employersList}
        />
        <div>
          <div className="flex justify-between items-center mb-4 p-6 md:px-24">
            <div
              className="relative h-12 w-72 cursor-pointer"
              onClick={() => router.push("/")}
            >
              <Image src="/logo.svg" fill alt="logo" />
            </div>
            <div className="hidden md:flex gap-4 items-center">
              <Dropdown
                title="Categories"
                list={categories.map((item) => ({
                  title: item.name,
                  route: `/categories/${item.id}`,
                }))}
              />
              <Dropdown title="Employers" list={employersList} />
              <Button variant="secondary">Post a Job</Button>
            </div>
            <button
              onClick={() => setOpenSidebar(true)}
              className="block md:hidden"
            >
              <Menu />
            </button>
          </div>

          {children}
        </div>
      </div>
      <GuestFooter categories={categories} employersList={employersList} />
      <Backdrop
        show={openSidebar}
        onClick={() => setOpenSidebar(false)}
        className="md:invisible"
      />
    </>
  );
}

export default GuestLayout;
